import Game from "types/Game";

const defaultGames: Game[] = [
  {
    board: {
      squares: [
        [
          {
            type: 4,
            x: 0,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 1,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 2,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 2,
            x: 3,
            y: 0,
            multiplier: 3,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 4,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 5,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 6,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 7,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 8,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 9,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 2,
            x: 11,
            y: 0,
            multiplier: 3,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 12,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 4,
            x: 14,
            y: 0,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 5,
            x: 0,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 1,
            y: 1,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 2,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 3,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 4,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 5,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 6,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 7,
            y: 1,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 8,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 9,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 11,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 12,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 13,
            y: 1,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 14,
            y: 1,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 5,
            x: 0,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 1,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 4,
            x: 2,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 3,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 4,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 5,
            y: 2,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 6,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 7,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 8,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 9,
            y: 2,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 11,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 4,
            x: 12,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 14,
            y: 2,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 2,
            x: 0,
            y: 3,
            multiplier: 3,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 1,
            y: 3,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 2,
            y: 3,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 3,
            y: 3,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 4,
            y: 3,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 5,
            y: 3,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 6,
            y: 3,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 7,
            y: 3,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 8,
            y: 3,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 9,
            y: 3,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 3,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 11,
            y: 3,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 12,
            y: 3,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 3,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 2,
            x: 14,
            y: 3,
            multiplier: 3,
            multiplyWord: true,
          },
        ],
        [
          {
            type: 5,
            x: 0,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 1,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 2,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 3,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 4,
            y: 4,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 5,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 6,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 7,
            y: 4,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 8,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 9,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 10,
            y: 4,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 11,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 12,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 14,
            y: 4,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 5,
            x: 0,
            y: 5,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 1,
            y: 5,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 2,
            y: 5,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 3,
            y: 5,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 4,
            y: 5,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 5,
            y: 5,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 6,
            y: 5,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 7,
            y: 5,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 8,
            y: 5,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 9,
            y: 5,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 5,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 11,
            y: 5,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 12,
            y: 5,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 5,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 14,
            y: 5,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 5,
            x: 0,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 1,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 2,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 3,
            y: 6,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 4,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 5,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 4,
            x: 6,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 7,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            letter: { stringValue: "F", scoreValue: 4 },
            type: 0,
            x: 8,
            y: 6,
            multiplier: 1,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 9,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 11,
            y: 6,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 12,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 14,
            y: 6,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 5,
            x: 0,
            y: 7,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 1,
            y: 7,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 2,
            y: 7,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 3,
            y: 7,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 4,
            y: 7,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 5,
            y: 7,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 6,
            y: 7,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            letter: { stringValue: "K", scoreValue: 3 },
            type: 0,
            x: 7,
            y: 7,
            multiplier: 1,
            multiplyWord: false,
          },
          {
            letter: { stringValue: "U", scoreValue: 4 },
            type: 0,
            x: 8,
            y: 7,
            multiplier: 1,
            multiplyWord: false,
          },
          {
            letter: { stringValue: "L", scoreValue: 2 },
            type: 0,
            x: 9,
            y: 7,
            multiplier: 1,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 10,
            y: 7,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 11,
            y: 7,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 12,
            y: 7,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 13,
            y: 7,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 14,
            y: 7,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 5,
            x: 0,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 1,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 2,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 3,
            y: 8,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 4,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 5,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 4,
            x: 6,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 7,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            letter: { stringValue: "X", scoreValue: 8 },
            type: 0,
            x: 8,
            y: 8,
            multiplier: 1,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 9,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 11,
            y: 8,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 12,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 14,
            y: 8,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 5,
            x: 0,
            y: 9,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 1,
            y: 9,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 2,
            y: 9,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 3,
            y: 9,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 4,
            y: 9,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 5,
            y: 9,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 6,
            y: 9,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 7,
            y: 9,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 8,
            y: 9,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 9,
            y: 9,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 9,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 11,
            y: 9,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 12,
            y: 9,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 9,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 14,
            y: 9,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 5,
            x: 0,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 1,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 2,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 3,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 4,
            y: 10,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 5,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 6,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 7,
            y: 10,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 8,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 9,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 10,
            y: 10,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 11,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 12,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 14,
            y: 10,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 2,
            x: 0,
            y: 11,
            multiplier: 3,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 1,
            y: 11,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 2,
            y: 11,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 3,
            y: 11,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 4,
            y: 11,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 5,
            y: 11,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 6,
            y: 11,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 7,
            y: 11,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 8,
            y: 11,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 9,
            y: 11,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 11,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 11,
            y: 11,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 12,
            y: 11,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 11,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 2,
            x: 14,
            y: 11,
            multiplier: 3,
            multiplyWord: true,
          },
        ],
        [
          {
            type: 5,
            x: 0,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 1,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 4,
            x: 2,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 3,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 4,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 5,
            y: 12,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 6,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 7,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 8,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 3,
            x: 9,
            y: 12,
            multiplier: 2,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 11,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 4,
            x: 12,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 14,
            y: 12,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 5,
            x: 0,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 1,
            y: 13,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 2,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 3,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 4,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 5,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 6,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 7,
            y: 13,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 8,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 9,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 11,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 12,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 1,
            x: 13,
            y: 13,
            multiplier: 2,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 14,
            y: 13,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
        [
          {
            type: 4,
            x: 0,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 1,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 2,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 2,
            x: 3,
            y: 14,
            multiplier: 3,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 4,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 5,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 6,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 7,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 8,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 9,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 10,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 2,
            x: 11,
            y: 14,
            multiplier: 3,
            multiplyWord: true,
          },
          {
            type: 5,
            x: 12,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 5,
            x: 13,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
          {
            type: 4,
            x: 14,
            y: 14,
            multiplier: 3,
            multiplyWord: false,
          },
        ],
      ],
      playerState: {
        userId: 748338,
        hand: [
          { stringValue: "I", scoreValue: 1 },
          { stringValue: "R", scoreValue: 1 },
          { stringValue: "A", scoreValue: 1 },
          { stringValue: "G", scoreValue: 1 },
          { stringValue: "Ä", scoreValue: 1 },
          { stringValue: "M", scoreValue: 1 },
          { stringValue: "G", scoreValue: 1 },
        ],
        score: 18,
        handCount: 7,
      },
      opponentState: {
        userId: 793551,
        score: 40,
        handCount: 7,
      },
    },
    player: {
      id: 748338,
      handle: "DavidRdrgz",
      name_first: "David",
      name_last: "Rodriguez",
      age: 1980,
      location: 28,
      gender: 1,
      location_text: "Danderyd",
      rating: 1139,
      won: 51,
      droped: 2,
      drawn: 0,
      games: 133,
      bingos: 32,
    },
    opponent: {
      id: 793551,
      handle: "oliverlevay",
      name_first: "Oliver",
      name_last: "Levay",
      age: 1999,
      gender: 1,
      location_text: "Danderyd",
      rating: 1000,
      won: 0,
      droped: 0,
      drawn: 0,
      games: 0,
      bingos: 0,
    },
  },
];

export default defaultGames;
